# Generated by Django 2.0 on 2017-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armor',
            name='protection',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
