# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0005_auto_20171219_2359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monsterdamagetypeperc',
            unique_together=set([('monster', 'damage_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='monsterweapontyperelation',
            unique_together=set([('monster', 'weapon_type')]),
        ),
    ]
