# Generated by Django 2.0 on 2017-12-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0005_auto_20171219_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WitcherEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witcher_event', to='WitcherZeroPlayerGame.Witcher')),
                ('witcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witcher', to='WitcherZeroPlayerGame.Witcher')),
            ],
        ),
    ]
