# Generated by Django 2.0 on 2017-12-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0007_auto_20171220_2313'),
        ('WitcherZeroPlayerGame', '0006_event_witcherevent'),
    ]

    operations = [
    ]
