# Generated by Django 2.0 on 2017-12-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0008_merge_20171223_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witcher',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='witcherevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witcher_event', to='WitcherZeroPlayerGame.Event'),
        ),
    ]
