# Generated by Django 2.0 on 2017-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0009_auto_20171223_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witcherevent',
            name='event',
            field=models.CharField(max_length=200),
        ),
    ]
