# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0010_auto_20171223_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WitcherZeroPlayerGame.WitcherSchool'),
        ),
    ]
