# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0011_auto_20171227_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
