# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0012_monster_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageperc',
            name='name',
            field=models.IntegerField(),
        ),
    ]
