# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0013_auto_20171227_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damageperc',
            old_name='name',
            new_name='value',
        ),
    ]
