# Generated by Django 2.0 on 2017-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0014_auto_20171227_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='possible_bad_events',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='possible_good_events',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='possible_neutral_events',
            field=models.IntegerField(default=10),
        ),
    ]
