# Generated by Django 2.0 on 2017-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0015_auto_20171227_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='possible_bad_events',
            new_name='possible_negative_events',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='possible_good_events',
            new_name='possible_positive_events',
        ),
    ]
