# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitcherZeroPlayerGame', '0016_auto_20171227_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageperc',
            name='value',
        ),
        migrations.AddField(
            model_name='damageperc',
            name='name',
            field=models.CharField(default='dfd', max_length=50),
            preserve_default=False,
        ),
    ]
